# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('change_time', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ChangeOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.FloatField()),
                ('batch', models.CharField(max_length=32)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.ChangeOrder')),
            ],
        ),
        migrations.CreateModel(
            name='CheckOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('check_time', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CheckOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.FloatField()),
                ('batch', models.CharField(max_length=32)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.CheckOrder')),
            ],
        ),
        migrations.CreateModel(
            name='KucunOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('how', models.IntegerField(choices=[(0, '\u8fdb\u8d27'), (1, '\u9500\u552e'), (2, '\u52a0\u5de5'), (3, '\u76d8\u70b9'), (4, '\u8c03\u62e8')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='KucunOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.FloatField()),
                ('batch', models.CharField(max_length=32)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.KucunOrder')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGoodsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=64)),
                ('work_time', models.CharField(max_length=64)),
                ('kucun_in_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_in', to='stock.KucunOrder')),
                ('kucun_out_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_order_out', to='stock.KucunOrder')),
                ('warehouse_in', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_house_in', to='base.Warehouse')),
                ('warehouse_out', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_house_out', to='base.Warehouse')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGoodsOrderDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(max_length=32)),
                ('num', models.FloatField()),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Goods')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.WorkGoodsOrder')),
            ],
        ),
        migrations.AddField(
            model_name='checkorder',
            name='kucun_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stock.KucunOrder'),
        ),
        migrations.AddField(
            model_name='checkorder',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Warehouse'),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='kucun_in_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_in', to='stock.KucunOrder'),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='kucun_out_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_out', to='stock.KucunOrder'),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='warehouse_in',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_in', to='base.Warehouse'),
        ),
        migrations.AddField(
            model_name='changeorder',
            name='warehouse_out',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='house_out', to='base.Warehouse'),
        ),
    ]
