# -*- coding:utf-8 -*-
"""
Django settings for sh_psi project.

Generated by 'django-admin startproject' using Django 1.11.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'l_=hqr(r-c9^@dpx+ax(28r4v_e&aq#i2@=)butfj4d692owh1'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'auto_account',
    'base',
    'purchase_sales',
    'report',
    'stock',
    'login',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    # 'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'sh_psi.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'sh_psi.wsgi.application'

# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'dami',
        'USER': 'psi',
        'PASSWORD': 'psi1024',
        'HOST': '127.0.0.1',
        'PORT': '3306',
        # 'TEST': {
        #     'NAME': 'sh_psi_test',
        #     'CHARSET': 'utf8',  # charset关键字大小写,utf8,utf8mb4
        #     'COLLATION': 'utf8_general_ci',
        # },
    }
}

# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')
LOGIN_URL = '/static/html/login.html'
# FIXTURE_DIRS = (os.path.join(BASE_DIR, 'Sale/fixtures/'),)

# LOGGING = {
#     'version': 1,
#     'disable_existing_loggers': False,
#     'filters': {
#         'require_debug_true': {
#             '()': 'django.utils.log.RequireDebugTrue',
#         },  # 针对 DEBUG = True 的情况
#     },
#     'formatters': {
#         'standard': {
#             'format': '[%(asctime)s] [%(levelname)s] %(message)s'
#         },  # 对日志信息进行格式化
#     },
#     'handlers': {
#         'mail_admins': {
#             'level': 'ERROR',
#             'class': 'django.utils.log.AdminEmailHandler',
#             'formatter': 'standard'
#         },
#         'file_handler': {
#             'level': 'INFO',
#             'class': 'logging.handlers.TimedRotatingFileHandler',
#             'filename': './log/log.log',
#             'formatter': 'standard'
#         },  # 用于文件输出
#         'console': {
#             'level': 'DEBUG',
#             'filters': ['require_debug_true'],
#             'class': 'logging.StreamHandler',
#             'formatter': 'standard'
#         },
#     },
#     'loggers': {
#         'django': {
#             'handlers': ['file_handler', 'console'],
#             'level': 'INFO',
#             'propagate': True  # 是否继承父类的log信息
#         },  # handlers 来自于上面的 handlers 定义的内容
#     }
# }
qiniu_config = {
    'AK': 'tG86zAtcQTDOtwN1aQGBa4-6ULkvKCcV7azRAcHE',
    'SK': 'EuUIXfgs1SA1TjDHtRrDLhWl8rnPIWB6zP-mTDmH',
    'BUCKET_NAME': 'refund-test',
    'DOMAIN': 'http://test.qiniu.liujh.site/'
}
IMAGES_DIR = BASE_DIR + '/images/'

__cpid = 'wwa0cf2e58e87c0d10'
__csecret = 'pR2c5vqRea4meCSGOeC4BME1Z-TSf4hW4Sr50cv2O7M'
WORK_WEIXIN_CONFIG = {
    'corpid': __cpid,  # 企业id,本企业员工才可以进
    'corpsecret': __csecret,  # 企业secret
    'agentid': '1000041',  # 应用id，代理应用id
    'access_token_url': 'https://qyapi.weixin.qq.com/cgi-bin/gettoken',
    'get_userid_url': 'https://qyapi.weixin.qq.com/cgi-bin/user/getuserinfo',
    'get_user_info_url': 'https://qyapi.weixin.qq.com/cgi-bin/user/get',
    'jsapi_ticket_url': 'https://qyapi.weixin.qq.com/cgi-bin/get_jsapi_ticket',
    'app_jsapi_ticket_url': 'https://qyapi.weixin.qq.com/cgi-bin/ticket/get',
    'redirect_uri': 'psi/login/confirm_login',
}
# ----------------------------------------------回调页面---------------------------------------------- #
# 用户授权获取code后的回调页面，如果需要实现验证登录就必须填写
BASE_URL = 'http://refund-test.liujh.site'
REDIRECT_URI = BASE_URL + '/refund/wechat/index'
PC_LOGIN_REDIRECT_URI = BASE_URL + '/refund/wechat/index'
defaults = {
    # 微信内置浏览器获取code微信接口
    'wechat_browser_code': 'https://open.weixin.qq.com/connect/oauth2/authorize',
    # 微信内置浏览器获取access_token微信接口
    'wechat_browser_access_token': 'https://api.weixin.qq.com/sns/oauth2/access_token',

    # 微信内置浏览器获取用户信息微信接口
    'wechat_browser_user_info': 'https://api.weixin.qq.com/sns/userinfo',
    # 'wechat_browser_user_info': 'https://api.weixin.qq.com/sns/oauth2/component/access_token',
    # pc获取登录二维码接口
    'pc_QR_code': 'https://open.weixin.qq.com/connect/qrconnect',
    # pc获取登录二维码接口
    # 'pc_QR_code': 'https://api.weixin.qq.com/sns/userinfo',
    # 支付下单接口
    'order_url': 'https://api.mch.weixin.qq.com/pay/unifiedorder',
    'notify_url': BASE_URL + '/wechat/success/',
}
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
        }
    }
}
SESSION_COOKIE_AGE = 3600 * 24  # 一天session有效期
