# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 07:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('tel', models.CharField(max_length=32)),
                ('contacts', models.CharField(max_length=32)),
                ('addr', models.CharField(max_length=64)),
                ('account', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(0, '\u4e0d\u542f\u7528\u53ef\u89c1'), (1, '\u542f\u7528\u53ef\u89c1'), (2, '\u5220\u9664\u4e0d\u53ef\u89c1\u4e86')], default=1)),
                ('remarks', models.CharField(max_length=32)),
                ('type', models.IntegerField(choices=[(0, '\u4f9b\u5e94\u5546'), (1, '\u987e\u5ba2')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Goods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('rec_price', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('sale_price', models.FloatField()),
                ('status', models.IntegerField(choices=[(0, '\u4e0d\u542f\u7528\u53ef\u89c1'), (1, '\u542f\u7528\u53ef\u89c1'), (2, '\u5220\u9664\u4e0d\u53ef\u89c1\u4e86')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Goods_Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('status', models.IntegerField(choices=[(0, '\u4e0d\u542f\u7528\u53ef\u89c1'), (1, '\u542f\u7528\u53ef\u89c1'), (2, '\u5220\u9664\u4e0d\u53ef\u89c1\u4e86')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('comment', models.CharField(max_length=64)),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Power',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=16, unique=True)),
                ('sub_spec', models.CharField(max_length=16)),
                ('status', models.IntegerField(choices=[(0, '\u4e0d\u542f\u7528\u53ef\u89c1'), (1, '\u542f\u7528\u53ef\u89c1'), (2, '\u5220\u9664\u4e0d\u53ef\u89c1\u4e86')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=32)),
                ('work_id', models.IntegerField(unique=True)),
                ('job', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(0, '\u5931\u6548'), (1, '\u6709\u6548')], default=1)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('power', models.ManyToManyField(default=None, to='base.Power')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('addr', models.CharField(max_length=32)),
                ('tel', models.CharField(max_length=32)),
                ('contacts', models.CharField(max_length=32)),
                ('status', models.IntegerField(choices=[(0, '\u4e0d\u542f\u7528\u53ef\u89c1'), (1, '\u542f\u7528\u53ef\u89c1'), (2, '\u5220\u9664\u4e0d\u53ef\u89c1\u4e86')], default=1)),
                ('volume', models.FloatField()),
                ('type', models.IntegerField(choices=[(1, '\u4ed3\u5e93'), (2, '\u95e8\u5e97')], default=1)),
                ('storage_state', models.IntegerField(choices=[(0, '\u5df2\u6ee1'), (1, '\u672a\u6ee1'), (2, '\u7a7a')])),
                ('create_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='goods',
            name='goods_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Goods_Class'),
        ),
        migrations.AddField(
            model_name='goods',
            name='spec',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Spec'),
        ),
    ]
