# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='status',
            field=models.IntegerField(choices=[(0, '\u505c\u7528'), (1, '\u542f\u7528'), (2, '\u5220\u9664/\u5931\u6548')], default=1),
        ),
        migrations.AlterField(
            model_name='goods',
            name='status',
            field=models.IntegerField(choices=[(0, '\u505c\u7528'), (1, '\u542f\u7528'), (2, '\u5220\u9664/\u5931\u6548')], default=1),
        ),
        migrations.AlterField(
            model_name='goods_class',
            name='status',
            field=models.IntegerField(choices=[(0, '\u505c\u7528'), (1, '\u542f\u7528'), (2, '\u5220\u9664/\u5931\u6548')], default=1),
        ),
        migrations.AlterField(
            model_name='spec',
            name='status',
            field=models.IntegerField(choices=[(0, '\u505c\u7528'), (1, '\u542f\u7528'), (2, '\u5220\u9664/\u5931\u6548')], default=1),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='status',
            field=models.IntegerField(choices=[(0, '\u505c\u7528'), (1, '\u542f\u7528'), (2, '\u5220\u9664/\u5931\u6548')], default=1),
        ),
    ]
