# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-05 07:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('stock', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetailOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.FloatField()),
                ('price', models.FloatField()),
                ('need_price', models.FloatField()),
                ('new_need_price', models.FloatField()),
                ('batch', models.CharField(max_length=32, null=True)),
                ('goods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Goods')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=32, unique=True)),
                ('type', models.IntegerField(choices=[(0, '\u8fdb\u8d27\u8ba2\u5355'), (1, '\u9500\u552e\u8ba2\u5355')])),
                ('cabinets', models.CharField(blank=True, max_length=32)),
                ('send_way', models.CharField(max_length=32)),
                ('count_type', models.IntegerField(choices=[(0, '\u73b0\u7ed3\u4ed8\u6e05'), (1, '\u73b0\u7ed3\u672a\u4ed8\u6e05'), (2, '\u6708\u7ed3'), (3, '\u6279\u7ed3')])),
                ('real_price', models.FloatField()),
                ('need_price', models.FloatField()),
                ('approval_status', models.IntegerField(choices=[(0, '\u672a\u5ba1\u6279'), (1, '1\u7ea7\u901a\u8fc7'), (2, '1\u7ea7\u62d2\u7edd')], default=0)),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('order_status', models.IntegerField(choices=[(0, '\u65e0\u6548/\u8349\u7a3f'), (1, '\u6709\u6548')], default=1)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Client')),
                ('kucun_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stock.KucunOrder')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.Warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='detailorder',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='purchase_sales.Order'),
        ),
    ]
