# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-07 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_sales', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='approval_status',
            field=models.IntegerField(choices=[(0, '\u5ba1\u6838\u4e2d'), (1, '\u5ba1\u6838\u901a\u8fc7'), (2, '\u5ba1\u6838\u5931\u8d25')], default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='count_type',
            field=models.IntegerField(choices=[(0, '\u73b0\u7ed3\u4ed8\u6e05'), (1, '\u73b0\u7ed3\u672a\u4ed8\u6e05'), (2, '\u6708\u7ed3\u4ed8\u6e05'), (3, '\u6708\u7ed3\u672a\u4ed8\u6e05'), (4, '\u6279\u7ed3\u4ed8\u6e05'), (5, '\u6279\u7ed3\u672a\u4ed8\u6e05')]),
        ),
    ]
