# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_sales', '0002_auto_20190307_1703'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='count_type',
            field=models.IntegerField(choices=[(0, '\u73b0\u7ed3\u7ed3\u8d26'), (1, '\u73b0\u7ed3\u672a\u7ed3\u8d26'), (2, '\u6708\u7ed3\u7ed3\u8d26'), (3, '\u6708\u7ed3\u672a\u7ed3\u8d26'), (4, '\u6279\u7ed3\u7ed3\u8d26'), (5, '\u6279\u7ed3\u672a\u7ed3\u8d26')]),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[(0, '\u65e0\u6548/\u5220\u9664'), (1, '\u6709\u6548')], default=1),
        ),
    ]
