# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-08 07:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auto_account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientincome',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
